### ISSUE TITLE
Prompt besser erkennen

### ISSUE THREAD

**Issue by Kebap** [MorgenGrauen/krrrcks-mudlet#3]
@MorgenGrauen/contrib-mudlet Hi Zesstra, könntest du hier einige Details beantworten? Die Mudlet Entwickler wollen ggf. das Telnet-Modul austauschen und dabei auf Standards zurückgreifen. Wär super, wenn in dem Zug auch direkt der MorgenGrauen Standard enthalten wäre - heute wird der MG Prompt leider noch nicht automatisch von Mudlet erkannt. Dazu gab es einige Rückfragen, Danke!

Siehe hier: https://github.com/Mudlet/Mudlet/issues/1252

**Comment by Kebap** [comment]
Ich sehe hier Zesstra als Teilnehmer von MorgenGrauen: https://github.com/orgs/MorgenGrauen/people

Aber ich kann nicht direkt per @Zesstra oder so ähnlich adressieren - mache ich etwas falsch?

**Comment by krrrcks** [comment]
Hm. vielleicht weil er nicht hier in diesem Repository tätig ist? Wobei er doch mal was eingestellt hatte, oder? Ansonsten kann man ihn irgendwie "hinzuholen"?

**Comment by zesstra** [comment]
Offenbar funktioniert das @zesstra aber schon, denn hier an dem Issue steht für mich: You’re receiving notifications because you were mentioned.
Ich habe bei dem Mudlet issue was kommentiert. Wobei ich keine Ahnung habe, was Mudlib da nun eigentlich tut, aber das müssen die ja erstmal selber wissen... ;-)

**Comment by Kebap** [comment]
Das ist inzwischen umgesetzt worden 👍
